version: "3"
networks:
  elastic:
    external: true
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.12.0
    networks:
      - elastic
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    restart: always
    deploy:
      resources:
        limits:
          memory: 1Gb
    cap_add:
      - IPC_LOCK
  kibana:
    container_name: kibana
    image: kibana:8.12.0
    networks:
      - elastic
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

